# Generated by Django 5.1 on 2024-08-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_deliverymethod_paymentmethod_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('standard', 'Стандартная доставка'), ('express', 'Экспресс-доставка'), ('pickup', 'Самовывоз')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('credit_card', 'Кредитная карта'), ('paypal', 'PayPal'), ('cash_on_delivery', 'Оплата при доставке')], default='credit_card', max_length=20),
        ),
    ]
