# Generated by Django 5.1 on 2024-08-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_report_expenses_report_profit_alter_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
