# Generated by Django 5.1 on 2024-08-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_report_date_alter_report_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sales_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
