# Generated by Django 5.1 on 2024-08-16 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_review_created_at_review_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 16, 6, 19, 43, 688935, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
